export interface articulos {

    ARTICULO :string
    PLANTILLA_SERIE? :string
    DESCRIPCION :string
    CLASIFICACION_1? :string
    CLASIFICACION_2? :string
    CLASIFICACION_3? :string
    CLASIFICACION_4? :string
    CLASIFICACION_5? :string
    CLASIFICACION_6? :string
    FACTOR_CONVER_1? :number
    FACTOR_CONVER_2? :number
    FACTOR_CONVER_3? :number
    FACTOR_CONVER_4? :number
    FACTOR_CONVER_5? :number
    FACTOR_CONVER_6? :number
    TIPO :string
    ORIGEN_CORP :string
    PESO_NETO :number
    PESO_BRUTO :number
    VOLUMEN :number
    BULTOS :number
    ARTICULO_CUENTA :string
    IMPUESTO :string
    FACTOR_EMPAQUE :number
    FACTOR_VENTA :number
    EXISTENCIA_MINIMA :number
    EXISTENCIA_MAXIMA :number
    PUNTO_DE_REORDEN :number
    COSTO_FISCAL :string
    COSTO_COMPARATIVO :string
    COSTO_PROM_LOC :number
    COSTO_PROM_DOL :number
    COSTO_STD_LOC :number
    COSTO_STD_DOL :number
    COSTO_ULT_LOC :number
    COSTO_ULT_DOL :number
    PRECIO_BASE_LOCAL :number
    PRECIO_BASE_DOLAR :number
    ULTIMA_SALIDA :Date
    ULTIMO_MOVIMIENTO :Date
    ULTIMO_INGRESO :Date
    ULTIMO_INVENTARIO :Date
    CLASE_ABC :string
    FRECUENCIA_CONTEO :number
    CODIGO_BARRAS_VENT? :string
    CODIGO_BARRAS_INVT? :string
    ACTIVO :string
    USA_LOTES :string
    OBLIGA_CUARENTENA :string
    MIN_VIDA_COMPRA :number
    MIN_VIDA_CONSUMO :number
    MIN_VIDA_VENTA :number
    VIDA_UTIL_PROM :number
    DIAS_CUARENTENA :number
    PROVEEDOR? :string
    ARTICULO_DEL_PROV? :string
    ORDEN_MINIMA :number
    PLAZO_REABAST :number
    LOTE_MULTIPLO :number
    NOTAS? :string
    UTILIZADO_MANUFACT :string
    USUARIO_CREACION? :string
    FCH_HORA_CREACION? :Date
    USUARIO_ULT_MODIF? :string
    FCH_HORA_ULT_MODIF? :Date
    USA_NUMEROS_SERIE :string
    MODALIDAD_INV_FIS? :string
    TIPO_COD_BARRA_DET? :string
    TIPO_COD_BARRA_ALM? :string
    USA_REGLAS_LOCALES? :string
    UNIDAD_ALMACEN :string
    UNIDAD_EMPAQUE :string
    UNIDAD_VENTA :string
    PERECEDERO :string
    GTIN? :string
    MANUFACTURADOR? :string
    CODIGO_RETENCION? :string
    RETENCION_VENTA? :string
    RETENCION_COMPRA? :string
    MODELO_RETENCION? :string
    ESTILO? :string
    TALLA? :string
    COLOR? :string
    TIPO_COSTO :string
    ARTICULO_ENVASE? :string
    ES_ENVASE :string
    USA_CONTROL_ENVASE :string
    COSTO_PROM_COMPARATIVO_LOC :number
    COSTO_PROM_COMPARATIVO_DOLAR :number
    COSTO_PROM_ULTIMO_LOC :number
    COSTO_PROM_ULTIMO_DOL :number
    UTILIZADO_EN_CONTRATOS :string
    VALIDA_CANT_FASE_PY :string
    OBLIGA_INCLUIR_FASE_PY :string
    ES_IMPUESTO :string
    NoteExistsFlag :number
    RecordDate :Date
    RowPointer :string
    CreatedBy :string
    UpdatedBy :string
    CreateDate :Date
    U_COD_ANTIGUO? :string
    TIPO_DOC_IVA? :string
    NIT? :string
    CANASTA_BASICA :string
    ES_OTRO_CARGO :string
    SERVICIO_MEDICO :string
    item_hacienda? :string
    CODIGO_HACIENDA? :string
    ITEM_HACIENDA_COMPRA? :string
    TIENDA :string
    TIPO_EXISTENCIA? :string
    CATALOGO_EXISTENCIA? :string
    TIPO_DETRACCION_VENTA? :string
    CODIGO_DETRACCION_VENTA? :string
    TIPO_DETRACCION_COMPRA? :string
    CODIGO_DETRACCION_COMPRA? :string
    CALC_PERCEP :string
    PORC_PERCEP? :number
    U_MONEDA_VENTA_BEEPOS? :string
    U_BARRA_VENTA_BEEPOS? :string
    U_COD_ANTIGUO_SUPER? :string
    
}