export interface cliente {
    cliente: string
    nombre: string
    detalle_Direccion?:  number
    alias?: string
    contacto: string
    cargo: string
    direccion?: string
    dir_Emb_Default?: string
    telefono1: string
    telefono2: string
    fax: string
    contribuyente: string
    fecha_Ingreso: Date
    multimoneda: string
    moneda: string
    saldo:  number
    saldo_Local:  number
    saldo_Dolar: number
    saldo_Credito: number
    saldo_Nocargos?: number
    limite_Credito?: number
    exceder_Limite: string
    tasa_Interes: number
    tasa_Interes_Mora: number
    fecha_Ult_Mora: Date
    fecha_Ult_Mov: Date
    condicion_Pago: string
    nivel_Precio: string
    descuento: number
    moneda_Nivel: string
    acepta_Backorder: string
    pais: string
    zona: string
    ruta: string
    vendedor?: string
    cobrador: string
    acepta_Fracciones: string
    activo: string
    exento_Impuestos: string
    exencion_Imp1: number
    exencion_Imp2: number
    cobro_Judicial: string
    categoria_Cliente: string
    clase_Abc?: string
    dias_Abastecimien: number
    usa_Tarjeta: string
    tarjeta_Credito?: string
    tipo_Tarjeta?: string
    fecha_Vence_Tarj?: Date
    e_Mail?: string
    requiere_Oc: string
    es_Corporacion: string
    cli_Corporac_Asoc?: string
    registrardocsacorp: string
    usar_Diremb_Corp: string
    aplicac_Abiertas: string
    verif_Limcred_Corp: string
    usar_Desc_Corp: string
    doc_A_Generar: string
    rubro1_Cliente?: string
    rubro2_Cliente?: string
    rubro3_Cliente?: string
    tiene_Convenio: string
    notas?: string
    dias_Promed_Atraso:  number
    rubro1_Cli?: string
    rubro2_Cli?: string
    rubro3_Cli?: string
    rubro4_Cli?: string
    rubro5_Cli?: string
    asocobligcontfact: string
    rubro4_Cliente?: string
    rubro5_Cliente?: string
    rubro6_Cliente?: string
    rubro7_Cliente?: string
    rubro8_Cliente?: string
    rubro9_Cliente?: string
    rubro10_Cliente?: string
    usar_Precios_Corp: string
    usar_Exencimp_Corp: string
    dias_De_Cobro?: string
    ajuste_Fecha_Cobro: string
    gln?: string
    ubicacion?: string
    clase_Documento: string
    local: string
    tipo_Contribuyente?: string
    rubro11_Cliente?: string
    rubro12_Cliente?: string
    rubro13_Cliente?: string
    rubro14_Cliente?: string
    rubro15_Cliente?: string
    rubro16_Cliente?: string
    rubro17_Cliente?: string
    rubro18_Cliente?: string
    rubro19_Cliente?: string
    rubro20_Cliente?: string
    Modelo_Retencion?: string
    acepta_Doc_Electronico: string
    confirma_Doc_Electronico: string
    email_Doc_Electronico?: string
    email_Ped_Edi?: string
    acepta_Doc_Edi: string
    Notificar_Error_Edi: string
    email_Error_Ped_Edi?: string
    codigo_Impuesto?: string
    division_Geografica1?: string
    division_Geografica2?: string
    regimen_Trib?: string
    Moroso: string
    Modif_Nomb_En_Fac: string
    saldo_Trans:  number
    saldo_Trans_Local:  number
    saldo_Trans_Dolar:  number
    Permite_Doc_Gp: string
    Participa_Flujocaja: string
    curp?: string
    usuario_Creacion?: string
    fecha_Hora_Creacion?: Date
    usuario_Ult_Mod?: string
    fch_Hora_Ult_Mod?: Date
    email_Doc_Electronico_Copia?: string
    detallar_Kits: string
    Xslt_Personalizado?: string
    Nombre_Addenda?: string
    geo_Latitud?:  number
    geo_Longitud?:  number
    division_Geografica3?: string
    division_Geografica4?: string
    Otras_Senas?: string
    subtipodoc?: string
    api_Recepcion_De?: string
    usa_Api_Recepcion?: string
    user_Api_Recepcion?: string
    Pass_Api_Recepcion?: string
    noteExistsFlag:  number
    recordDate: Date
    rowPointer: string
    createdby: string
    updatedby: string
    createdate: Date
    u_Sexo?: string
    u_Fecha_Nac?: Date
    u_Nentradas?:  number
    u_Ultent?: Date
    u_Identidad?: string
    u_Compania?: string
    u_Procedencia?: string
    u_Parentesco?: string
    u_Autoriza?: string
    u_Unidad_Militar?: string
    u_Numero_Unico?: string
    u_Codigo_Vam?: string
    u_Ultima_Carta?: Date
    u_Fecha_Venc_Contrato?: Date
    u_Proceso?: Date
    u_Estadocivil?: string
    u_Telefono1?: string
    u_Telefono2?: string
    u_Dependientes?:  number
    u_Vigencia?: Date
    tipo_Impuesto?: string
    tipo_Tarifa?: string
    porc_Tarifa?:  number
    Tipificacion_Cliente?: string
    afectacion_Iva?: string
    es_Extranjero: string
    item_Hacienda?: string
    xslt_Personalizado_Credito?: string
    tipo_Generar?: string
    tipo_Personeria?: string
    uso_Cfdi?: string
    metodo_Pago?: string
    banco_Nacion?: string
    es_Agente_Percepcion: string
    es_Buen_Contribuyente: string
    u_Saldo_Feria?:  number
    u_Credito_Feria?:  number
    u_EsMilitar?: string
    u_EsEmpleado?: string
    u_MontoInicial?: number
    u_SaldoDisponible?: number
    u_Descuento?: number


/*
    montoInicial?:  number
    montoDisponible?: number;*/

}