export interface facturas {    
    tipo_Documento: string
    factura: string
    audit_Trans_Inv?: number
    esta_Despachado: string
    en_Investigacion: string
    trans_Adicionales: string
    estado_Remision: string
    asiento_Documento?: string
    descuento_Volumen: number
    moneda_Factura: string
    comentario_Cxc?: string
    fecha_Despacho: Date
    clase_Documento: string
    fecha_Recibido: Date
    pedido?: string
    factura_Original?: string
    tipo_Original?: string
    comision_Cobrador: number
    tarjeta_Credito?: string
    total_Volumen: number
    numero_Autoriza?: string
    total_Peso: number
    monto_Cobrado: number
    total_Impuesto1: number
    fecha: Date
    fecha_Entrega: Date
    total_Impuesto2: number
    porc_Descuento2: number
    monto_Flete: number
    monto_Seguro: number
    monto_Documentacio: number
    tipo_Descuento1: string
    tipo_Descuento2: string
    monto_Descuento1: number
    monto_Descuento2: number
    porc_Descuento1: number
    total_Factura: number
    fecha_Pedido: Date
    fecha_Hora_Anula?: Date
    fecha_Orden?: Date
    total_Mercaderia: number
    comision_Vendedor: number
    orden_Compra?: string
    fecha_Hora: Date
    total_Unidades: number
    numero_Paginas: number
    tipo_Cambio: number
    anulada: string
    modulo: string
    cargado_CG: string
    cargado_CXC: string
    embarcar_A: string
    direc_Embarque?: string
    direccion_Factura?: string
    multiplicador_Ev: number
    observaciones?: string
    rubro1?: string
    rubro2?: string
    rubro3?: string
    rubro4?: string
    rubro5?: string
    version_NP: number
    moneda: string
    nivel_Precio: string
    cobrador: string
    ruta: string
    usuario: string
    usuario_Anula?: string
    condicion_Pago: string
    zona: string
    vendedor: string
    doc_Credito_Cxc?: string
    cliente_Direccion: string
    cliente_Corporac: string
    cliente_Origen: string
    cliente: string
    pais: string
    subtipo_Doc_CXC?: number
    tipo_Credito_Cxc?: string
    tipo_Doc_CXC?: string
    monto_Anticipo?: number
    total_Peso_Neto?: number
    fecha_Rige: Date
    contrato?: string
    porc_Intcte?: number
    usa_Despachos: string
    cobrada: string
    descuento_Cascada: string
    direccion_Embarque?: string
    consecutivo?: string
    reimpreso: number
    division_Geografica1?: string
    division_Geografica2?: string
    base_Impuesto1?: number
    base_Impuesto2?: number
    nombre_Cliente?: string
    doc_Fiscal?: string
    nombremaquina?: string
    serie_Resolucion?: string
    consec_Resolucion?: number
    genera_Doc_Fe: string
    tasa_Impositiva?: string
    tasa_Impositiva_Porc?: number
    tasa_Cree1?: string
    tasa_Cree1_Porc?: number
    tasa_Cree2?: string
    tasa_Cree2_Porc?: number
    tasa_Gan_Ocasional_Porc?: number
    contrato_Ac?: string
    ajuste_Redondeo?: number
    uso_Cfdi?: string
    forma_Pago?: string
    clave_Referencia_De?: string
    fecha_Referencia_De?: Date
    justi_Dev_Haciend?: string
    incoterms?: string
    u_Ad_Wm_Numero_Vendedor?: string
    u_Ad_Wm_Enviar_Gln?: string
    u_Ad_Wm_Numero_Recepcion?: string
    u_Ad_Wm_Numero_Reclamo?: string
    u_Ad_Wm_Fecha_Reclamo?: string
    u_Ad_Pc_Numero_Vendedor?: string
    u_Ad_Pc_Enviar_Gln?: string
    u_Ad_Gs_Numero_Vendedor?: string
    u_Ad_Gs_Enviar_Gln?: string
    u_Ad_Gs_Numero_Recepcion?: string
    u_Ad_Gs_Fecha_Recepcion?: string
    u_Ad_Am_Numero_Proveedor?: string
    u_Ad_Am_Enviar_Gln?: string
    u_Ad_Am_Numero_Recepcion?: string
    u_Ad_Am_Numero_Reclamo?: string
    u_Ad_Am_Fecha_Reclamo?: string
    u_Ad_Am_Fecha_Recepcion?: string
    tipo_Operacion?: string
    noteExistsFlag: number
    recordDate: Date
    rowPointer: string
    createdBy: string
    updatedBy: string
    createDate: Date
    clave_De?: string
    actividad_Comercial?: string
    monto_Otro_Cargo?: number
    monto_Total_Iva_Devuelto?: number
    codigo_Referencia_De?: string
    tipo_Referencia_De?: string
    cancelacion?: string
    estado_Cancelacion?: string
    tiene_Relacionados?: string
    prefijo?: string
    fecha_Inicio_Resolucion?: Date
    fecha_Final_Resolucion?: Date
    clave_Tecnica?: string
    matricula_Mercantil?: number
    es_Factura_Reemplazo?: string
    factura_Original_Reemplazo?: string
    consecutivo_Ftc?: string
    numero_Ftc?: string
    nit_Transportador?: string
    ncf_Modificado?: string
    num_Oc_Exenta?: string
    num_Cons_Reg_Exo?: string
    num_Irsede_Agr_Gan?: string
    u_Ad_Wm_Tipo_Nc?: string
    cuenta_Asiento?: string
    tipo_Pago?: string
    tipo_Descuento_Global?: string
    tipo_Factura?: string
    tipo_Nc?: string
    tipo_Detrac?: string
    act_Detrac?: string
    porc_Detrac?: number


}