export interface factura_linea {    
    factura: string
    tipo_Documento: string
    linea: number
    bodega: string
    costo_Total_Dolar: number
    pedido?: string
    articulo: string
    localizacion?: string
    lote?: string
    anulada: string
    fecha_Factura: Date
    cantidad: number
    precio_Unitario: number
    total_Impuesto1: number
    total_Impuesto2: number
    desc_Tot_Linea: number
    desc_Tot_General: number
    costo_Total: number
    precio_Total: number
    descripcion?: string
    comentario?: string
    cantidad_Devuelt: number
    descuento_Volumen: number
    tipo_Linea: string
    cantidad_Aceptada: number
    cant_No_Entregada: number
    costo_Total_Local: number
    pedido_Linea?: number
    multiplicador_Ev: number
    serie_Cadena?: number
    serie_Cad_No_Acept?: number
    serie_Cad_Aceptada?: number
    documento_Origen?: string
    linea_Origen?: number
    tipo_Origen?: string
    unidad_Distribucio?: string
    cant_Despachada: number
    costo_Estim_Local: number
    costo_Estim_Dolar: number
    cant_Anul_Pordespa?: number
    monto_Retencion: number
    base_Impuesto1?: number
    base_Impuesto2?: number
    proyecto?: string
    fase?: string
    centro_Costo?: string
    cuenta_Contable?: string
    costo_Total_Comp: number
    costo_Total_Comp_Local: number
    costo_Total_Comp_Dolar: number
    costo_Estim_Comp_Local: number
    costo_Estim_Comp_Dolar: number
    cant_Dev_Proceso: number
    noteExistsFlag: number
    recordDate: Date
    rowPointer: string
    createdBy: string
    updatedBy: string
    createDate: Date
    tipo_Impuesto1?: string
    tipo_Tarifa1?: string
    tipo_Impuesto2?: string
    tipo_Tarifa2?: string
    porc_Exoneracion?: number
    monto_Exoneracion?: number
    es_Otro_Cargo?: string
    es_Canasta_Basica?: string
    es_Servicio_Medico?: string
    monto_Devuelto_Iva?: number
    porc_Exoneracion2?: number
    monto_Exoneracion2?: number
    tipo_Descuento_Linea?: string
}